/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.shnewto.assertlike;

public class AssertlikeApp {
    public String getGreeting() {
        return "Hello Assertlike User \uD83D\uDC4B";
    }

    public static void main(String[] args) {
        System.out.println(new AssertlikeApp().getGreeting());
    }
}
